### ISSUE TITLE
Cannot import the module on NEXTJS - window is not undefined 

### ISSUE THREAD

**Issue by scottbolasevich** [barnjamin/algorand-session-wallet#6]
import { SessionWallet, PermissionResult, SignedTxn, Wallet} from 'algorand-session-wallet'

just trying a basic import.. i also tried 
const SessionWallet = dynamic(() => import('algorand-session-wallet'),{ ssr: false })

and

import('algorand-session-wallet').then((sWallet) => {
});

**Comment by barnjamin** [comment]
The act of setting the session vars tries to call window methods, I'm not sure what the right way to reference it is in nextjs but if you figure out maybe we can have some way to pass a ref to the window?

**Comment by barnjamin** [comment]
I'm not sure where the `window is not undefined` is coming from but I'm guessing it has to do with https://github.com/barnjamin/algorand-session-wallet/blob/main/src/index.ts#L133 + server side referencing.

Here is a project that uses this repo as its session wallet for reference:
https://github.com/barnjamin/arc3.xyz

**Comment by scottbolasevich** [comment]
yup that's what i found too. turned out to be related to this https://github.com/randlabs/communication-bridge/issues/5

**Comment by scottbolasevich** [comment]
fyi easiest fix just upgrade your package.json from  1.1.2 to "@randlabs/myalgo-connect": "^1.1.3" they fixed it in this commit

https://github.com/randlabs/myalgo-connect/commit/534e2be0cc268a6767f645a4e5204c3c3d05e0b2
